name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Clear Go cache
      run: |
        go clean -cache
        go clean -modcache
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run go vet
      run: go vet ./...

    - name: Run gofmt check
      run: |
        # Check if code is properly formatted
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted properly. Please run 'gofmt -s -w .' locally and commit the changes."
          echo "Files that need formatting:"
          gofmt -s -l .
          exit 1
        else
          echo "Code is properly formatted"
        fi

    - name: Build for current platform
      run: go build -v ./...

  build:
    name: Build Cross Platform
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for multiple platforms
      run: |
        # Build for Linux (amd64)
        GOOS=linux GOARCH=amd64 go build -o movie-tinder-linux-amd64 .
        
        # Build for macOS (amd64)
        GOOS=darwin GOARCH=amd64 go build -o movie-tinder-darwin-amd64 .
        
        # Build for Windows (amd64)
        GOOS=windows GOARCH=amd64 go build -o movie-tinder-windows-amd64.exe .

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: movie-tinder-binaries
        path: |
          movie-tinder-linux-amd64
          movie-tinder-darwin-amd64
          movie-tinder-windows-amd64.exe