name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Clear Go cache
      run: |
        go clean -cache
        go clean -modcache
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run go vet
      run: go vet ./...

    - name: Run gofmt
      run: |
        # Format code first
        gofmt -s -w .
        
        # Check if there are any changes after formatting
        if [ -n "$(git status --porcelain)" ]; then
          echo "Code was not properly formatted. Auto-formatted files:"
          git diff --name-only
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-format code with gofmt"
          git push
        else
          echo "Code is already properly formatted"
        fi

    - name: Build for current platform
      run: go build -v ./...

  build:
    name: Build Cross Platform
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for multiple platforms
      run: |
        # Build for Linux (amd64)
        GOOS=linux GOARCH=amd64 go build -o movie-tinder-linux-amd64 .
        
        # Build for macOS (amd64)
        GOOS=darwin GOARCH=amd64 go build -o movie-tinder-darwin-amd64 .
        
        # Build for Windows (amd64)
        GOOS=windows GOARCH=amd64 go build -o movie-tinder-windows-amd64.exe .

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: movie-tinder-binaries
        path: |
          movie-tinder-linux-amd64
          movie-tinder-darwin-amd64
          movie-tinder-windows-amd64.exe